url: http://www.mrtim.co.uk
baseurl: 

# Site settings
title: English with Mr Tim
email: timjlamb@aol.com
description: "Portfolio English Programme with Mr Tim"


# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty