url: https://www.mrtim.co.uk
baseurl: 

# Site settings
title: English with Mr Tim
email: tim@timjlamb.com
description: "Portfolio English Programme with Mr Tim"


# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"